[package]
name = "callisto"
version = "0.0.1"
entrypoint = "src/callisto.typ"
authors = ["Jeremie Knuesel <https://github.com/knuesel>"]
license = "MIT"
description = "Import Jupyter notebooks"
repository = "https://github.com/knuesel/callisto"
keywords = ["jupyter", "notebook", "import"]
categories = ["integration", "utility"]
exclude = ["/tests/*"]
compiler = "0.13.1"
